routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('config:clear');
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('config:cache');
    $exitCode = Artisan::call('view:cache');
    return 'DONE'; //Return anything
});
Route::get('localization/{locale}','LocalizationController@lang');

Route::get('/', 'WelcomeController@index')->name('welcome.page');
// Route::post('/price/filter','WelcomeController@filterprice')->name('price.filter');

// Route::get('/layouts3', 'WelcomeController@layout')->name('layouts.new');
// show View all , Special , New , Popular , Top Selling Prodcts


Route::get('/new/arrival','WelcomeController@newarrival')->name('new.arrival');
Route::get('/hot/product','WelcomeController@hotproduct')->name('hot.product');
Route::get('/feature/product','WelcomeController@featureproduct')->name('feature.product');
Route::get('/category/list/{id}','WelcomeController@Categorylist')->name('category.list');
Route::get('/Subcategory/list/{id}','WelcomeController@SubCategorylist')->name('subcategory.list');
Route::get('/deals','WelcomeController@deals');


Route::get('/products/list/{id}','WelcomeController@productslist')->name('products.list');

Route::get('setpassword/{token}','EmailController@setpassword');

Route::get('sendemail','EmailController@sendemail');

Route::get('/careers','WelcomeController@careers');
Route::post('/careers','WelcomeController@careersPost');

Route::get('/faq','WelcomeController@faq');
Route::POST('/faq','WelcomeController@faqPost');

Route::get('/contact','WelcomeController@contact');

Route::get('/termsandconditions','WelcomeController@termsandconditions');

Route::get('/privacyandpolicy','WelcomeController@privacyandpolicy');

Route::get('/about','WelcomeController@about');

Route::get('/help','WelcomeController@help');

Route::post('sendproductemail','WelcomeController@sendproductemail');

Route::post('subscribe','WelcomeController@subscribe');

// cart added
Route::post('/cart/add/{id}','WelcomeController@cartadd')->name('cart.added');
Route::get('/checkout/cart','WelcomeController@checkoutcart')->name('checkout.cart');
Route::post('/quantity/update/{rowId}','WelcomeController@Qtyupdate')->name('quantity.update');
Route::get('remove/cart/{rowId}','WelcomeController@removeCart')->name('remove.cart');

Auth::routes();

    Route::post('password/reset','EmailController@passwordreset');
    Route::post('set_passwordPost','EmailController@set_passwordPost');

    Route::get('/checkout-form' , 'HomeController@checkoutForm')->name('checkout.form');
    Route::post('/city/change' , 'HomeController@CityChange')->name('city.change');
    Route::post('/checout-form/post' , 'HomeController@Checkoutpost')->name('checkout-form.post');
    Route::get('/checkout/pay/{order}', 'HomeController@payView')->name('checkout.pay');
    Route::get('/transaction/pay/{id}' ,'HomeController@pay')->name('transaction');
    // Route::get('/api-test' ,'HomeController@pay')->name('pay.success');
    Route::get('/payredirect' ,'HomeController@payredirect')->name('redirect.success');
    Route::post('/tap/post' ,'HomeController@tapPost')->name('tap.post');
    Route::post('/tap/charge' ,'HomeController@tapCharge')->name('tap.charge');

    // Route::post('/cart/add/{id}','HomeController@cartadd')->name('cart.added');
    Route::get('/wishlist/add/{id}','HomeController@wishlist')->name('wishlist.add');
    // Route::get('/wishlist/update/{id}','HomeController@wishlistUpdate')->name('wishlist.update');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/customer/dashboard', 'HomeController@CustomerDashboard')->name('customer.dashboard');
    Route::get('/cart/items/{id}', 'HomeController@show')->name('cartitem.show');

// admin Middleware Section
Route::get('/admin/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
Route::post('/admin/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');

Route::get('/delivery/agents/login', 'Auth\AdminLoginController@showDeliveryLoginForm')->name('delivery.login');
Route::post('/delivery/agents/login', 'Auth\AdminLoginController@showDeliveryLoginFormPost')->name('delivery.login.submit');
Route::get('/delivery/agents/register', 'Auth\AdminLoginController@showDeliveryRegisterForm')->name('delivery.register');
Route::post('/delivery/agents/register', 'Auth\AdminLoginController@showDeliveryRegisterFormPost')->name('delivery.register.submit');



Route::prefix('delivery/agents')->middleware('checkdelivery')->group(function(){
    Route::get('/', 'DeliveryController@index')->name('delivery.dashboard');
    Route::get('/orders', 'deliveryagents\SalesController@index');

    Route::get('/orders/items/{id}', 'deliveryagents\SalesController@orderagentapproved')->name('order.agentapprove');
});

Route::prefix('admin')->middleware('auth:admin')->group(function() {
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/logout','Auth\AdminLoginController@logout')->name('admin.logout');

    Route::get('/main-categories' , 'CategoriesController@mainCategory')->name('main-categories');
    Route::get('/main-categories/form' , 'CategoriesController@mainCategoryForm')->name('main-categories.form');
    Route::post('/main-categories/create' , 'CategoriesController@mainCategoryCreate')->name('main-categories.create');

    //  Product dropdown route
    Route::get('/categories','CategoriesController@index');
    Route::get('/categories/form','CategoriesController@create');
    Route::post('/categories/form','CategoriesController@store')->name('add.categories');
    Route::get('/categories/form/{id}','CategoriesController@edit')->name('edit.categories');
    Route::post('/categories/form/{id}','CategoriesController@update')->name('update.categories');
    Route::get('/categories/delete{id}','CategoriesController@delete')->name('delete.categories');
    Route::get('/categories/trash','CategoriesController@categoriesTrash')->name('trash.categories');
    Route::get('/subcategories','CategoriesController@subcategories');
    Route::get('/subcategories/form','CategoriesController@subcategoriesform');
    Route::post('/subcategories/form','CategoriesController@subcategoriesformpost');

    Route::get('/subcategories/edit/{id}','CategoriesController@subcategoriesformedit');
    Route::post('/subcategories/formeditpost','CategoriesController@subcategoriesformeditpost');
    
    Route::post('/getcategories', 'CategoriesController@getcategories');
    Route::post('/getsubcategories', 'CategoriesController@getsubcategories');

    // subcategories delet
    Route::get('/subcategories/delete/{id}','CategoriesController@subcategories_delet')->name('subcategories.delete');
    Route::get('/subcategories/trash','CategoriesController@trashsubcategories')->name('trash.subcategories');


//    Route::get('/banners','ContentContrroller@index');

    Route::get('/brands','CategoriesController@brands');
    Route::get('/barnds/add','CategoriesController@addbrands')->name('add.brands');
    Route::post('/barnds/store','CategoriesController@storebrands')->name('brands.create');
    Route::get('/brands/edit/{id}','CategoriesController@editbrand')->name('brands.edit');
    Route::post('/brands/update/{id}','CategoriesController@updatebrand')->name('brnads.update');
    Route::get('/brands/delete/{id}','CategoriesController@deletebrand')->name('brnads.delete');
    Route::get('/brands/trash','CategoriesController@trashbrand')->name('brands.trash');

    Route::get('/products','CategoriesController@products');
    Route::get('/products/add','CategoriesController@addproducts')->name('add.products');
    Route::post('/products/addformpost','CategoriesController@addproductspost');
    Route::get('/products/edit/{id}','CategoriesController@editproduct');
    Route::post('/products/editpost/{id}','CategoriesController@editproductpost');
    Route::get('/products/delete/{id}','CategoriesController@productdelete')->name('product.delete');
    Route::get('/products/trash','CategoriesController@producttrash')->name('trash.products');
    Route::post('/Img/remove/{id}','CategoriesController@imgDelete')->name('img.delete');


    Route::post('/products/deleteproductattribute','CategoriesController@deleteproductattribute');


    Route::post('/products/filter/categories','CategoriesController@Filterbycategoru')->name('categories.filter');

    Route::get('/pages','CategoriesController@information');
    Route::get('/pages/add','CategoriesController@pagesadd');
    Route::post('/pages/addpost','CategoriesController@pagesaddpost');

    Route::get('/pages/addlink','CategoriesController@pagesaddlink');
    Route::post('/pages/addlinkpost','CategoriesController@pagesaddlinkpost');

    // Promotion Dropdown route
    
    Route::get('/product_offers', 'PromotionController@product_offers');
    Route::get('/product_offers/form','PromotionController@add_product_wise_offer')->name('products.offers');
    Route::get('/product_offers/edit/{id}', 'PromotionController@product_offersedit');
    Route::post('/product_offers/formpostedit','PromotionController@product_formpostedit');
    Route::get('/product_offers/delete/{id}','PromotionController@product_offers_delete')->name('product_offer.delete');
    Route::post('/product_offers/formpost','PromotionController@product_offerspost');

    Route::post('/getsubcategoryproducts','PromotionController@getsubcategoryproducts');
    Route::post('/getsubcategoryproducts1','PromotionController@getsubcategoryproducts1');

app/Orderitem.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Orderitem extends Model
{
    //
    protected $table = 'orderitem';

    public function product()
    {
        return $this->belongsTo(products::class);
    }

    public function getBarCodeAttribute()
    {
        $barcode = Productattributes::where('id',$this->color_id)->first();
        if(isset($barcode))
        {
            return $barcode->sku;
        }
        return null
       ;
    }
}

app/products.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class products extends Model
{
    //

    protected $table = 'products';

    public function order_item()
    {
       return $this->hasMany(Orderitem::class, 'product_id');
    }

    public function productQuantity()
    {
       return $this->hasMany(Productattributes::class, 'productid');
    }

    public function getDiscountedPriceAttribute()
    {
       if ($this->promotion_type == 'product' || $this->promotion_type == 'subcategory') {
          if ($this->promotion_type == 'product') {
            $discount = product_promotions::where('id' ,$this->all_offers)->where('disable_on_utc', '>', now())->first();
          } else {
            $discount = subcategory_promotions::where('id' ,$this->all_offers)->where('disable_on_utc', '>', now())->first();
          }
          if ($discount) {
            return ((100 - $discount->percentage) * $this->price) / 100;
          }
       }
       return null;
    }
  
   public function getVatAttribute() 
   {
      $price = $this->discounted_price ?? $this->price;
      return ($price * config('cart.tax')) / 100;
   }

   public function getMainImageAttribute()
   {
      $images = json_decode($this->image);
      if (isset($images[0])) {
         return asset('public/images/products/'.$images[0]);
      }
      return null;
   }

   public function getTotalAttribute()
   {
      $price = $this->discounted_price ?? $this->price;
      return $this->vat + $price;
   }

}   
   

resources/views/front-end/careers.blade.php
@extends('layouts.front-app')

@section('content')
<style>
    .c1 h1
    {
        color: #39509c;
        font-family: sans-serif;
    }
    .c1 p
    {
        color: black;
        font-family: sans-serif;
    }
    h2
    {
        color: #39509c;
        font-family: sans-serif;
    }
    label
    {
        color: black;
    }
</style>
<section class="pb-5" >
    <div class="container">
        <div class="c1" style="background: #fff;">
            <h1>{{ trans('careers.Job Portal') }}</h1>
            <p>{{ trans('careers.Achieving success by respecting and empowering personal potential.') }}</p>
            <p>{{ trans('careers.Our passion and ingenuity fuels inspired design. We are always looking for talented, dedicated and passionate teammates who want to carve their own path exploring technological innovation in engineering. Visit our careers page to find out more!') }}</p>
            <br>
            <b><p>{{ trans('careers.There is no job available right now. Kindly upload your CV we will contact you asap.') }}</p></b>
        </div>

        @if ($message = Session::get('success'))
        <div class="alert alert-success alert-block">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>{{ $message }}</strong>

        </div>
        @endif
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        <form method="POST" action="{{ url('careers') }}" enctype="multipart/form-data">
            @csrf
            <br>
            <div class="form-group input-group">
                <input class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}"  placeholder="{{ trans('careers.Your Name') }}" type="text">

            </div>

            <div class="form-group input-group">
                <input class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" placeholder="{{ trans('careers.Your Email') }}" type="email">
            </div>

            <div class="form-group input-group">
                <input class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="phonenumber" value="{{ old('email') }}" placeholder="{{ trans('careers.Phone Number') }}" type="text">
            </div>

            <div class="form-group input-group">
                <input class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="jobtitle" value="{{ old('email') }}" placeholder="{{ trans('careers.Job Title') }}" type="text">
            </div>

            <div class="form-group input-group">

                <input type="file" name="document">
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block"> {{ trans('careers.Register') }}  </button>
                <br>
                <button  class="btn btn-success btn-block"> {{ trans('careers.Back') }}  </button>
            </div>
           
        </form>

    </div>


</section>
@endsection

resources/views/front-end/checkout.blade.php
@extends('layouts.front-app')
@section('content')

{{-- @php 
$cartCount = 0;
if (auth()->check()) {
    $cartCount = \App\Cart::where(['user_id' => auth()->id(), 'status' => 0])->get();
    $productclist = 
}
@endphp --}}

@if (\Session::has('danger'))
<div class="alert alert-danger">
<h3>{{ \Session::get('danger') }} </h3>
</div>
@endif


<div class="px-4 px-lg-0">
	<div class="pb-5">
        @php 
        $cartCount = Cart::count();
        @endphp
        
		@if($cartCount != 0)
		<div class="container py-5 text-center">
			<h2>{{ trans('checkout.Your Cart') }}</h2>
		</div>
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-12 pl-5 pr-5 bg-white rounded">
					<div class="table-responsive">
						<table class="table cart-table" cellspacing="0">
							<thead>
								<tr>
									<th class="product-remove">&nbsp;</th>
									<th class="product-thumbnail">{{ trans('checkout.Image') }}</th>
									<th class="product-name">{{ trans('checkout.Product') }}</th>
									<th class="product-color">{{ trans('checkout.Color') }}</th>
									<th class="product-price">{{ trans('checkout.Price') }}</th>
									<th class="product-quantity">{{ trans('checkout.Quantity') }}</th>
									
									<th class="product-subtotal">{{ trans('checkout.Total') }}</th>
								</tr>
							</thead>
							<tbody>
                               
								@foreach ($cart as $item)
								@php $product = $item->product; @endphp

									<tr>
										<td class="product-remove">
											<a href="{{route('remove.cart',$item->rowId)}}" class="remove">
												<i class="fa fa-times"></i>
											</a>						
										</td>
										
										<td class="product-thumbnail">
                                            @foreach (json_decode($product->image) as $key => $products)
												@if($key == 0)
												<a href="#">
													<img width="100" width="100" src="{{asset('public/images/products/'.$products)}}" class="img-fluid rounded shadow-sm" alt="" >
												</a>
												@endif
                                            @endforeach
                                           
										</td>
										
										<td class="product-name">
										<a href="#">
                                            @if(\Session::get('locale') == 'ar')
                                            {{$product->arabic_name}}
                                            @else
                                            {{$product->prod_name}}
                                            @endif
                                        </a>
										</td>
										@php $options = []; @endphp
										@foreach ($item->attributes as $attributeKey => $option)
											@php $options[] = ucfirst($attributeKey == 'color' ? $option->name : $option); @endphp
										@endforeach
										
										<td style="font-weight: bold;color:#000;">
											{{ implode(', ', $options) }}
										</td>

										<td class="product-price">
											<span class="amount">
												<bdi>
													<span class="currencySymbol">{{ trans('checkout.SR') }}</span>
                                                    {{$item->price}}
												</bdi>
											</span>
										</td>
										<form action="{{route('quantity.update',$item->rowId)}}" method="post">
											@csrf
											<td class="product-quantity" style="text-align: -webkit-center;">
												<div class="number-input md-number-input">
													<button onclick="this.parentNode.querySelector('input[type=number]').stepDown()" class="minus"></button>
													<input class="quantity" min="1" name="quantity" value="{{$item->qty}}" type="number">
													<button onclick="this.parentNode.querySelector('input[type=number]').stepUp()" class="plus"></button>
												</div>
											</td>
										</form>
										<td class="product-subtotal">
											<span class="price-amount amount">
												<bdi>
													<span class="currencySymbol">{{ trans('checkout.SR') }}</span> {{$item->total}}
												</bdi>
											</span>						
										</td>
									</tr>
								@endforeach
								
							</tbody>
						</table>
					</div>
				</div>
			</div>
			@php 
				$subTotal = Cart::subtotal();
				$vat = number_format((config('cart.tax') * $subTotal) / 100, 2);
				$total = number_format($subTotal + $vat, 2 );
				
			@endphp
			<div class="row bg-white">
                <div class="col-lg-6">
					<a href="{{ url('/') }}" type="button" style="    margin-top: 300px;" class="btn btn-dark  btn-primary">{{ trans('checkout.Continue Shoping') }}</a>
				</div>
                <div class="col-lg-6 rounded-pill">
					<div class="px-4 py-3 text-uppercase font-weight-bold" style="font-size:30px;">{{ trans('checkout.Cart totals') }}
					</div>
				  	<div class="p-4" style="border: 1px solid;">
					    <ul class="list-unstyled mb-4">
					    	<li class="d-flex justify-content-between py-3 border-bottom">
								<strong class="text-muted">{{ trans('checkout.Order Subtotal') }} </strong>
								
							<strong>{{ trans('checkout.SR') }} {{number_format($subTotal, 2)}}</strong>
					    	</li>
					      
					      	<li class="d-flex justify-content-between py-3 border-bottom">
							  <strong class="text-muted">{{ trans('checkout.VAT') }} {{config('cart.tax')}}%</strong>
					      		<strong>{{ trans('checkout.SR') }} {{$vat}}</strong>
							  </li>
							<li class="d-flex justify-content-between py-3 border-bottom">
								<strong class="text-muted">{{ trans('checkout.Total') }}</strong>
								
							<h5 class="font-weight-bold"> {{ $total}}</h5>
							</li>
					    </ul>
				    	<a href="{{route('checkout.form')}}" class="btn btn-dark rounded py-2 btn-block btn-primary">{{ trans('checkout.Procceed to checkout') }}</a>
				  </div>
				</div>
            </div>
	
        </div>
        @else
        
        <div class="text-center">
			<p>{{ trans('checkout.There are no items in this cart') }}</p>
        	<a href="{{ url('/') }}" type="button" class="btn btn-dark  btn-primary">{{ trans('checkout.Continue Shoping') }}</a>
        </div>
        @endif
       
  	</div>
</div>

@endsection

resources/views/front-end/help.blade.php
@extends('layouts.front-app')

@section('content')
<style>
   h1
   {
       font-size: 58px;
   }
</style>
<div class="container">
    <br>
    <br>
    <h1>{{ trans('help.Under Construction') }}</h1>
    <br>
    <br>
</div>
@endsection

resources/views/front-end/transaction.blade.php
@extends('layouts.front-app')
@section('content')

<div class="container">
    <div class="py-5 text-center">
        <h2>Payment</h2>
        <p class="lead">Need Some Informtion"</p>
    </div>
    <div class="stepwizard col-md-offset-3">
    	<div class="stepwizard-row setup-panel">
      		<div class="stepwizard-step">
        		<a href="#step-1" type="button" class="btn in-active-step btn-circle">1</a>
				<p>Account</p>
      		</div>
      		<div class="stepwizard-step">
        		<a href="#step-2" type="button" class="btn btn-default btn-circle in-active-step" disabled="disabled">2</a>
        		<p>Address</p>
      		</div>
      		<div class="stepwizard-step">
        		<a href="#step-3" type="button" class="btn btn-default btn-circle btn-primary" disabled="disabled">3</a>
        		<p>Payment</p>
      		</div>
    	</div>
  	</div>
    <div class="row">
        <div class="col-md-4 order-md-2 mt-4 mb-4 border-gray p-0">
            <div class="payment">
            	<h4 class="mt-3 ml-4">Cart - item(s)</h4>
            </div>	
			@foreach ($order->orderitems as $item)
				<div class="col-md-12 mt-4 mb-4 border-bottom-img">
					<div class="row product-container">
						<div class="col-md-4 col-sm-4 col-xs-4">
							<div class="product-img">
							<img src="{{optional($item->product)->main_image}}" class="img-thumbnail rounded">
							</div>
						</div>
						<div class="col-md-8 col-sm-8 col-xs-8">
							<p class="product-text">{{$item->product_name}}</p>
							<p>{{$item->product_quantity}} x  SR {{$item->product_unit_price}}</p>
							<p>{{ ucfirst($item->product_color) }}</p>

							@if($item->bar_code)
							<?php echo '<img src="data:image/png;base64,' . DNS1D::getBarcodePNG($item->bar_code, 'C39+',3,33,array(1,1,1), true) . '" alt="barcode" height="50" width="250"  />'; ?> 
							@endif
						</div>
					</div>	
				</div>
			@endforeach

    		<div class="payment">
            	<h4 class="mt-3 ml-4">Total</h4>
            </div>

    		<div class="col-md-12 mt-4 mb-4 border-bottom-img">
    			<div class="row product-container">
	        		<div class="col-md-12 col-sm-12 col-xs-12">
	            		<table class="table">
                			<tbody>
                				<tr>
                					<td> Subtotal:</td>
                					<td class="text-right">SR {{$order->subtotal}}</td>
                				</tr>
								<tr>
									<td>
										<strong>VAT:</strong>
									</td>
									<td class="text-right">
										<strong>SR {{$order->vat}}</strong>
									</td>
								</tr>
								<tr>
									<td>
										<strong>Shipping Price:</strong>
									</td>
									<td class="text-right">
										<strong>SR {{$order->shipping_price == '' ? 0 : $order->shipping_price}}</strong>
									</td>
								</tr>
  								<tr>
  									<td>
  										<strong>Total:</strong>
  									</td>
  									<td class="text-right">
  										<strong>SR {{ $order->total}}</strong>
  									</td>
								  </tr>
								  
                			</tbody>
						</table>
						
					
	        		</div>
	        	</div>	
    		</div>
        </div>

        <div class="col-md-8 order-md-1 mt-4 mb-4">
            <div class="row">
                <div class="col-md-6">
					<h4 class="mt-3 ">Billing Address</h4>
					<strong>Name</strong>
					<br>
					<small>Email</small>
					<br>
					<small>Mobile</small>
				</div>
				
				<div class="col-md-6">
					<h4 class="mt-3">Shipping Address</h4>
					<strong>Name</strong>
					<br>
					<small>Email</small>
					<br>
					<small>Mobile</small>
                </div>
            </div>
        	{{-- <div class="row mt-3">
                <div class="col-md-6">
                    <div class="payment">
                        <h4 class="mt-3 ml-4">Payment Methods</h4>
                    </div>
                    <div class="shipping">
                        <p>Bank Transfer</p>
                        <p>Cash on Delivery</p>
                        <p>
                            <img class="img-fluid cc-img payment-img" src="https://saidaliah.me/9/uploads/offer/visa-logo.jpg" />
                        </p>
                    </div>
                    <div class="custom-control custom-checkbox mt-3 mb-3">
                        <input type="checkbox" class="custom-control-input" id="agree-terms">
                        <label class="custom-control-label" for="agree-terms">
                            <a href="#" target="_blank">I have read and agree to the Terms & Conditions</a>
                        </label>
					</div>
					
                </div>
                
			</div> --}}
			
		</div>
		
	</div>
	<p id="demo"></p>
	@php $user = $order->user;@endphp
	<script type="text/javascript" src="https://goSellJSLib.b-cdn.net/v1.6.0/js/gosell.js"></script>
	<div id="root"></div>

	<div class="row">
		<div class="col-md-8"></div>
		<div class="col-md-4">
			<button id="openLightBox" onclick="goSell.openLightBox()" class="btn btn-success form-control" style="background:#39509c;font-size: 25px;height:60px;">Checkout</button>
			
		</div>
	</div>
	<br>
	
	
<script>

	goSell.config({
	"containerID": "root",
	"gateway": {
		"publicKey": "pk_test_gw06d87941vubZqis5zcNQTl",
		"merchantId": 3480289,
		"language": "en",
		"contactInfo": true,
		"supportedCurrencies": "all",
		"supportedPaymentMethods": "all",
		"saveCardOption": false,
		"customerCards": true,
		"notifications": "standard",
		"callback": function(response){ console.log('response', response); },
		"onClose": function(response){ console.log("onClose Event"); },
		"backgroundImg": {
			"url": "imgURL",
			"opacity": "0.5"
		},
		"labels": {
			"cardNumber": "Card Number",
			"expirationDate": "MM/YY",
			"cvv": "CVV",
			"cardHolder": "Name on Card",
			"actionButton": "Pay"
		},
		"style": {
			"base": {
				"color": "#535353",
				"lineHeight": "18px",
				"fontFamily": "sans-serif",
				"fontSmoothing": "antialiased",
				"fontSize": "16px",
				"::placeholder": {
				"color": "rgba(0, 0, 0, 0.26)",
				"fontSize": "15px"
				}
			},
			"invalid": {
				"color": "red",
				"iconColor": "#fa755a "
			}
		}
	},
	"customer": {
		"id": null,
		"first_name": "{{$user->name}}",
		"email": "{{$user->email}}",
		"phone": {
			"number": "{{$user->phone}}"
		}
	},
	"order": {
		"amount": "{{$order->total}}",
		"currency": "SAR",
		"items": @json($order->items),
		"shipping": null,
		"taxes": null
	},
	"transaction": {
		"mode": "charge",
		"charge": {
			"saveCard": false,
			"threeDSecure": true,
			"statement_descriptor": "Sample",
			"reference": {
				"transaction": "txn_0001",
				"order": "{{$order->id}}"
			},
			"metadata": {},
			"receipt": {
				"email": false,
				"sms": true
			},
			"redirect": "{{route('redirect.success')}}",
			"post": "{{route('tap.post')}}",
		}
	}
});

</script>
</div>
@endsection